### ISSUE TITLE
(Feature request) Support Parentheses and Order of Operations Handling

### ISSUE THREAD

**Issue by smed79** [FossifyOrg/Calculator#35] opened 2024-11-17 01:16 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calculator/issues) or [closed](https://github.com/FossifyOrg/Calculator/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calculator/discussions) or [closed](https://github.com/FossifyOrg/Calculator/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calculator/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

There are a gap relating to the handling of order of operations and the absence of parentheses support. This severely limits the app's functionality.

**Problem 1: Premature Evaluation**

The calculator evaluates expressions piecemeal instead of waiting for the complete input. For example, entering `1 + 1 + 1` results in `2` being displayed after the second "+" press, instead of waiting for the final "=" to calculate the correct sum of `3`.

**Problem 2: Missing Parentheses/Brackets**

The lack of parentheses/brackets `()` makes it impossible to perform calculations that require a specific order of operations. 

### Why do you want this feature?

These two issues combine to make even relatively simple calculations impossible. The calculator is effectively limited to single operations, severely restricting its usefulness.

Implement proper order of operations handling, including support for parentheses. This would allow users to enter complex expressions and ensure they are evaluated correctly.

A simple example like `10 - (10 - 1)` (which should equal 1) is not possible due to both the premature evaluation and the lack of parentheses support.

### Additional information

This issue needs to be addressed to make the calculator functional for anything beyond basic single-operator arithmetic.

Thank you for your time and attention to this matter.

**Comment by Aga-C** [comment] 2024-11-17 06:28
It's a duplicate of https://github.com/FossifyOrg/Calculator/issues/7.

**Closed by Aga-C** 2024-11-17 06:28 UTC
Labels: feature request, needs triage
